 export const startupDetails  =[


        {  name: 'Afia Pharma', category: 'Health', year: 2021, logo: require('../src/assets/2021/afia.svg') },
        { name: 'Afroduino', category: 'Other', year: 2021, logo: require('../src/assets/2021/afroduino.svg') },
        { name: 'Augmented Future', category: 'Education', year: 2021, logo: require('../src/assets/2021/augumented.svg') },
        { name: 'Aurrica', category: 'Other', year: 2021, logo: require('../src/assets/2021/aurrica.svg') },
        { name: 'Bafana', category: 'Other', year: 2021, logo: require('../src/assets/2021/bafana.svg') },
        { name: 'Bag', category: 'Software Development', year: 2021, logo: require('../src/assets/2021/bag.svg') },
        { name: 'Bookly Africa', category: 'Other', year: 2021, logo: require('../src/assets/2021/bookly-africa.svg') },
        { name: 'Doctor-Ai', category: 'Health', year: 2021, logo: require('../src/assets/2021/doctor-ai.svg') },
        { name: 'D-Travela', category: 'Other', year: 2021, logo: require('../src/assets/2021/d-travela.svg') },
        { name: 'Enlightenment-Lab', category: 'Software Development', year: 2021, logo: require('../src/assets/2021/enlightenment-lab.svg') },
        { name: 'E-shuri', category: 'Education', year: 2021, logo: require('../src/assets/2021/e-shuri.svg') },
        { name: 'Ewawe', category: 'Fintech', year: 2021, logo: require('../src/assets/2021/ewawe.svg') },
        { name: 'Explore', category: 'Education', year: 2021, logo: require('../src/assets/2021/explore.svg') },
        { name: 'Go Virtual', category: 'Software Development', year: 2021, logo: require('../src/assets/2021/govirtuals.svg') },
        { name: 'Greenalytic', category: 'Agriculture', year: 2021, logo: require('../src/assets/2021/greenalytics.svg') },
        { name: 'Hatch-Plus', category: 'Agriculture', year: 2021, logo: require('../src/assets/2021/hatch-plus.svg') },
        { name: 'Haraka Meds', category: 'Health', year: 2021, logo: require('../src/assets/2021/haraka-meds.svg') },
        { name: 'Hview-Tech', category: 'Software Development', year: 2021, logo: require('../src/assets/2021/hview-tech.svg') },
        { name: 'Insightiv', category: 'Software Development', year: 2021, logo: require('../src/assets/2021/insightiv.svg') },
        { name: 'Ironji', category: 'Other', year: 2021, logo: require('../src/assets/2021/ironji.svg') },
        { name: 'Ishema', category: 'Health', year: 2021, logo: require('../src/assets/2021/ishema.svg') },
        { name: 'Karisimbi', category: 'Health', year: 2021, logo: require('../src/assets/2021/karisimbi.svg') },
        { name: 'Kayko', category: 'Software Development', year: 2021, logo: require('../src/assets/2021/kayko.svg') },
        { name: 'Keya-Health', category: 'Health', year: 2021, logo: require('../src/assets/2021/keya-health.svg') },
        { name: 'Rurarera', category: 'Software Development ', year: 2021, logo: require('../src/assets/2021/rurarera.svg') },
        { name: 'RCGF', category: 'Other ', year: 2021, logo: require('../src/assets/2021/rcgf.svg') },
        { name: 'Magis', category: 'Other', year: 2021, logo: require('../src/assets/2021/magis.svg') },
        { name: 'MySquare Kilometers', category: 'Other ', year: 2021, logo: require('../src/assets/2021/mysqm.svg') },
        { name: 'Sangapesh', category: 'Fintech', year: 2021, logo: require('../src/assets/2021/sangapesh.svg') },
        { name: 'Shambapro', category: 'Agriculture', year: 2021, logo: require('../src/assets/2021/shamba-pro.svg') },
        { name: 'Second Life Storage', category: 'Other', year: 2021, logo: require('../src/assets/2021/second-life-storage.svg') },
        { name: 'Shuri Bus', category: 'Education', year: 2021, logo: require('../src/assets/2021/shuri-bus.svg') },
        { name: 'The Happynes', category: 'Other', year: 2021, logo: require('../src/assets/2021/the-happynes.svg') },
        { name: 'Tori', category: 'Other', year: 2021, logo: require('../src/assets/2021/tori.svg') },
        { name: 'Twis', category: 'Education', year: 2021, logo: require('../src/assets/2021/twis.svg') },
        { name: 'Vehisec', category: 'Transportation', year: 2021, logo: require('../src/assets/2021/vehisec.svg') },
        { name: 'VubaVuba', category: 'Other ', year: 2021, logo: require('../src/assets/2021/vuba-vuba.svg') },
        { name: 'Xtra-Tech', category: 'Other', year: 2021, logo: require('../src/assets/2021/xtra-tech.svg') },

        // 2022 startups.................
        { name: 'Bafana', category: 'Other', year: 2022, logo: require('../src/assets/2022/bafana.svg') },
        { name: 'Haraka Meds', category: 'Health', year: 2022, logo: require('../src/assets/2022/haraka-meds.svg') },
        { name: 'Health Edu', category: 'Health', year: 2022, logo: require('../src/assets/2022/health-edu.svg') },
        { name: 'Hiq Africa', category: 'Other', year: 2022, logo: require('../src/assets/2022/hiq-africa.svg') },
        { name: 'Huuza Quest ltd', category: 'Other', year: 2022, logo: require('../src/assets/2022/huza.svg') },
        { name: 'IT Consortium RWANDA', category: 'Other', year: 2022, logo: require('../src/assets/2022/it-consortium.svg') },
        { name: 'Imali', category: 'Other', year: 2022, logo: require('../src/assets/2022/imali.svg') },
        { name: 'School Nest', category: 'Education', year: 2022, logo: require('../src/assets/2022/school-nest.svg') },
        { name: 'Jo-Care', category: 'Health', year: 2022, logo: require('../src/assets/2022/jo-care.svg') },
        { name: 'Karisimbi', category: 'Health', year: 2022, logo: require('../src/assets/2022/karisimbi.svg') },
        { name: 'Kayko', category: 'Software Development', year: 2022, logo: require('../src/assets/2022/kayko.svg') },
        { name: 'Laina', category: 'Fintech', year: 2022, logo: require('../src/assets/2022/laina.svg') },
        { name: 'Larna', category: 'Education', year: 2022, logo: require('../src/assets/2022/larna.svg') },
        { name: 'Lifesten', category: 'Health', year: 2022, logo: require('../src/assets/2022/lifesten.svg') },
        { name: 'Magis', category: 'Other', year: 2022, logo: require('../src/assets/2022/magis-let.svg') },
        { name: 'Mulika Farms',
            description:'At Mulika farms we are creating a direct and transparent channel for sourcing agricultural produce directly from the farmer to market traders.We strive to improve farmers living standards by shortening the supply chain so that every farmer receives a fair market value for their crops.We have registered over 3,000 farmers. Our farmers have a 13% higher income compared to those who have not begun working with us.We have 50 buyers in our portfolio. Our Market Buyers have been able to save an average of 11% compared to non-Mulika platform buyers.We have moved over 140 tons of produce totaling to about 62,000 USD in transactions in just over 9 months, mostly potatoes and livestock (pigs).',

            category: 'Agriculture', year: 2022, logo: require('../src/assets/2022/mukika.svg') },
        { name: 'Mutware Educate', category: 'Education', year: 2022, logo: require('../src/assets/2022/mutware-educate.svg') },
        { name: 'MySquare Kilometers', category: 'Other ', year: 2022, logo: require('../src/assets/2022/mysqm.svg') },
        { name: 'Oazis Health', category: 'Health', year: 2022, logo: require('../src/assets/2022/oazis-health.svg') },
        { name: 'Paying Tone', category: 'Fintech', year: 2022, logo: require('../src/assets/2022/paying-tone.svg') },
        { name: 'School Nest', category: 'Education', year: 2022, logo: require('../src/assets/2022/school-nest.svg') },
        { name: 'Shambapro', category: 'Agriculture', year: 2022, logo: require('../src/assets/2022/shambapro.svg') },
        { name: 'Smart Ikigega', category: 'Agriculture', year: 2022, logo: require('../src/assets/2022/smart-ikigega.svg') },
        { name: 'Umurava', category: 'Software Development', year: 2022, logo: require('../src/assets/2022/umurava.svg') },
        { name: 'Uplus Mutual', category: 'Fintech', year: 2022, logo: require('../src/assets/2022/uplus-mutual.svg') },
        { name: 'UrId Technologies', category: 'Fintech', year: 2022, logo: require('../src/assets/2022/urid-technologies.svg') },
        { name: 'Viebeg', category: 'Fintech', year: 2022, logo: require('../src/assets/2022/viebeg.svg') },
        { name: 'Vitaway', category: 'Health', year: 2022, logo: require('../src/assets/2022/vitaway.svg') },

        //startups 2023....................
        { name: 'Abasare', category: 'Other', year: 2023, logo: require('../src/assets/2023/abasare.svg') },
        { name: 'Agri Nest', category: 'Agriculture', year: 2023, logo: require('../src/assets/2023/agri-nest.svg') },
        { name: 'Agri-Research Unguka', category: 'Agriculture', year: 2023, logo: require('../src/assets/2023/agriresearch-unguka.svg') },
        { name: 'Agrithink Tank', category: 'Agriculture', year: 2023, logo: require('../src/assets/2023/agrithink-tank.svg') },
        { name: 'Beyi Group', category: 'Other', year: 2023, logo: require('../src/assets/2023/beyi-group.svg') },
        { name: 'Bizcotap', category: 'Other', year: 2023, logo: require('../src/assets/2023/bizcotap.svg') },
        { name: 'Bookly Africa', category: 'Other', year: 2023, logo: require('../src/assets/2023/bookly-africa.svg') },
        { name: 'Bountiful Farmers', category: 'Agriculture', year: 2023, logo: require('../src/assets/2023/bountiful-farmers.svg') },
        { name: 'Bunga Bunga', category: 'Agriculture', year: 2023, logo: require('../src/assets/2023/bunga-bunga.svg') },
        { name: 'Care Connect', category: 'Health', year: 2023, logo: require('../src/assets/2023/care-connect.svg') },
        { name: 'Companion App', category: 'Other', year: 2023, logo: require('../src/assets/2023/companionapp.svg') },
        { name: 'Digital Health Line', category: 'Health', year: 2023, logo: require('../src/assets/2023/digital-health-line.svg') },
        { name: 'Dope', category: 'Health', year: 2023, logo: require('../src/assets/2023/dope.svg') },
        { name: 'Drop Wave', category: 'Other', year: 2023, logo: require('../src/assets/2023/dropwave.svg') },
        { name: 'Eazi Plug', category: 'Other', year: 2023, logo: require('../src/assets/2023/eazi-plug.svg') },
        { name: 'Groupeya', category: 'other', year: 2023, logo: require('../src/assets/2023/groupeya.svg') },
        { name: 'Hinia', category: 'Other', year: 2023, logo: require('../src/assets/2023/hinia.svg') },
        { name: 'Hova AI', category: 'Other', year: 2023, logo: require('../src/assets/2023/hova.svg') },
        { name: 'Ihuza', category: 'Health', year: 2023, logo: require('../src/assets/2023/ihuza.svg') },
        { name: 'Innova Hyper', category: 'Other', year: 2023, logo: require('../src/assets/2023/innovahyper.svg') },
        { name: 'Iraady', category: 'Other', year: 2023, logo: require('../src/assets/2023/iraady.svg') },
        { name: 'Irebe Biotech', category: 'Health', year: 2023, logo: require('../src/assets/2023/irebe-biotech.svg') },
        { name: 'Jenga Mo', category: 'Other', year: 2023, logo: require('../src/assets/2023/jenga-mo.svg') },
        { name: 'Kaaz App', category: 'Other', year: 2023, logo: require('../src/assets/2023/kaaz-app.svg') },
        { name: 'Kivu Health', category: 'Health', year: 2023, logo: require('../src/assets/2023/kivu-health.svg') },
        { name: 'Kuza', category: 'Other', year: 2023, logo: require('../src/assets/2023/kuza.svg') },
        { name: 'Lin Idea', category: 'Fintech', year: 2023, logo: require('../src/assets/2023/linidea.svg') },
        { name: 'Loopa', category: 'Agriculture', year: 2023, logo: require('../src/assets/2023/loopa.svg') },
        { name: 'Medixr', category: 'Education', year: 2023, logo: require('../src/assets/2023/medixr.svg') },
        { name: 'Mizero Care', category: 'Health', year: 2023, logo: require('../src/assets/2023/mizero-care.svg') },
        { name: 'My Kibo', category: 'Other', year: 2023, logo: require('../src/assets/2023/my-kibo.svg') },
        { name: 'Opina', category: 'Agriculture', year: 2023, logo: require('../src/assets/2023/opina.svg') },
        { name: 'Payws ltd', category: 'Other', year: 2023, logo: require('../src/assets/2023/payws-ltd.svg') },
        { name: 'Smart Class', category: 'Education', year: 2023, logo: require('../src/assets/2023/smart-class.svg') },
        { name: 'Splendid More', category: 'Other', year: 2023, logo: require('../src/assets/2023/splendid-more.svg') },
        { name: 'Technika', category: 'Education', year: 2023, logo: require('../src/assets/2023/technika.svg') },
        { name: 'Tekafrica ltd', category: 'Other', year: 2023, logo: require('../src/assets/2023/teka.svg') },
        { name: 'Tubimenye', category: 'Education', year: 2023, logo: require('../src/assets/2023/tubimenye-ltd.svg') },
        { name: 'Tuzaride', category: 'Other', year: 2023, logo: require('../src/assets/2023/tuzaride.svg') },
        { name: 'Urungano', category: 'Health', year: 2023, logo: require('../src/assets/2023/urungano.svg') },
        { name: 'WAD Holdings', category: 'Other', year: 2023, logo: require('../src/assets/2023/wad-holdings.svg') },
        { name: 'Wad Pharma', category: 'Health', year: 2023, logo: require('../src/assets/2023/wad-pharma.svg') },
        { name: 'Yagibaze', category: 'Education', year: 2023, logo: require('../src/assets/2023/yagibaze.svg') },
        { name: 'Yarn', category: 'Education', year: 2023, logo: require('../src/assets/2023/yarn.svg') },


        ]
 